# This is a basic workflow to help you get started with Actions
name: Deploy to S3 Learn Content Processor

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ${{ matrix.os }}
    environment: s3
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Configure AWS credentials from Production account
        uses: aws-actions/configure-aws-credentials@v2
        with:
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            aws-region: ${{ secrets.AWS_REGION }}
            role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Production - Upload to S3
        run: |
          aws s3 sync ./content/ s3://${{ secrets.AWS_S3_CONTENT_PROCESSOR_BUCKET }}/ \
          --exclude 'js/credentials.js' \
          --exclude '.git/*' \
          --exclude '.github/*' \
          --exclude '*.md' \
          --exclude '.vscode/*' \